[package]
name = "bevy_make_human"
description = "MakeHuman integration for Bevy"
repository = "https://github.com/slyedoc/bevy_make_human"
keywords = ["bevy", "makehuman", "gamedev"]
categories = ["game-development"]
authors = ["Patrick Towles <james.towles+bevy_make_human@gmail.com>"]
version = "0.1.1"
edition = "2024"

[features]
default = ["glossy_eyes", "debug_draw", "arkit"]
glossy_eyes = ["bevy/pbr_multi_layer_material_textures"]
arkit = []
debug_draw = ["bevy_mod_billboard", "bevy/default_font"]
raytrace = ["bevy/bevy_solari"]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", features = [
    "png", # png texture support
    "jpeg", # jpg texture support
] }
avian3d = { git = "https://github.com/slyedoc/avian", branch = "bevy-main" }

bevy-inspector-egui = { git = "https://github.com/slyedoc/bevy-inspector-egui", branch = "bevy-main" }

bevy_asset_loader = { git = "https://github.com/slyedoc/bevy_asset_loader", branch = "bevy-main", features = [
    "2d",
    "standard_dynamic_assets",
] }
bevy_blend_shapes = { git = "https://github.com/slyedoc/bevy_blend_shapes.git", branch = "main" }

obj = "0.10.2"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

strum = { version = "0.27", features = ["derive"] }
thiserror = "2.0"

# Optional debug_draw
bevy_mod_billboard = { git = "https://github.com/slyedoc/bevy_mod_billboard.git", branch = "bevy-main", optional = true }

[[example]]
name = "basic"
required-features = []

[[example]]
name = "feathers"
required-features = []

[[example]]
name = "arkit"
required-features = []

[[example]]
name = "animation"
required-features = []

[[example]]
name = "animation2"
required-features = []

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", features = [
    "bevy_dev_tools", # fps overlay
    "bevy_ui_debug", # ui debug
    "wav", # audio support
    "experimental_bevy_feathers",
] }
avian3d = { git = "https://github.com/slyedoc/avian", branch = "bevy-main", features = [
    "debug-plugin",
    "diagnostic_ui",
] }
bevy_mod_skinned_aabb = { git = "https://github.com/slyedoc/bevy_mod_skinned_aabb", branch = "bevy-main" }
bevy_mod_mipmap_generator = { git = "https://github.com/slyedoc/bevy_mod_mipmap_generator", branch = "bevy-main" }
bevy-inspector-egui = { git = "https://github.com/slyedoc/bevy-inspector-egui", branch = "bevy-main" }
bevy_enhanced_input = { git = "https://github.com/slyedoc/bevy_enhanced_input", branch = "bevy-main" }
bevy_egui = { git = "https://github.com/slyedoc/bevy_egui", branch = "bevy-main" }

# ui
bevy_ui_text_input = { git = "https://github.com/slyedoc/bevy_ui_text_input", branch = "bevy-main" }
cosmic-text = { version = "0.16" }


[build-dependencies]
serde_json = "1.0"

# optimization for dependencies in dev
[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
parry3d = { git = "https://github.com/slyedoc/parry", branch = "bevy-main" }
parry3d-f64 = { git = "https://github.com/slyedoc/parry", branch = "bevy-main" }
glamx = { git = "https://github.com/slyedoc/glamx", branch = "bevy-main" }
